"""Generate compact C++ gesture data from gestures/*.json before each build."""

import json
import re
from pathlib import Path

Import("env")

PROJECT_DIR = Path(env["PROJECT_DIR"])
GESTURE_DIR = PROJECT_DIR / "gestures"
OUTPUT_FILE = PROJECT_DIR / "src" / "generated" / "GestureData.h"


def cpp_identifier(value: str) -> str:
    identifier = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    if not identifier or identifier[0].isdigit():
        raise ValueError(f"Invalid gesture name for C++ identifier: {value!r}")
    return identifier


def load_gestures() -> list[dict]:
    gestures = []
    names = set()

    for path in sorted(GESTURE_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        name = data.get("spell")
        segments = data.get("segments")
        if not isinstance(name, str) or not name:
            raise ValueError(f"{path}: missing non-empty 'spell'")
        if name in names:
            raise ValueError(f"{path}: duplicate spell name {name!r}")
        if not isinstance(segments, list) or not segments:
            raise ValueError(f"{path}: 'segments' must be a non-empty list")

        total_length = 0
        checked_segments = []
        for index, segment in enumerate(segments):
            direction = segment.get("dir")
            length = segment.get("l")
            if not isinstance(direction, int) or not 0 <= direction <= 360:
                raise ValueError(f"{path}: segment {index} has invalid direction {direction!r}")
            if not isinstance(length, int) or length <= 0:
                raise ValueError(f"{path}: segment {index} has invalid length {length!r}")
            total_length += length
            # Keep the same normalization as test.py: 360 degrees equals 0 degrees.
            checked_segments.append((direction % 360, length))

        if total_length != 1000:
            raise ValueError(f"{path}: segment lengths add up to {total_length}, expected 1000")

        names.add(name)
        gestures.append({"name": name, "id": cpp_identifier(name), "segments": checked_segments})

    if not gestures:
        raise ValueError(f"No gesture files found in {GESTURE_DIR}")
    return gestures


def render_header(gestures: list[dict]) -> str:
    lines = [
        "// Generated by tools/generate_gestures.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "struct GestureSegment {",
        "    uint16_t direction;",
        "    uint16_t length;",
        "};",
        "",
        "struct GestureReference {",
        "    const char *name;",
        "    const GestureSegment *segments;",
        "    uint8_t segmentCount;",
        "};",
        "",
    ]

    for gesture in gestures:
        lines.append(f"static constexpr GestureSegment k{gesture['id'].title().replace('_', '')}Segments[] = {{")
        for direction, length in gesture["segments"]:
            lines.append(f"    {{{direction}, {length}}},")
        lines.extend(["};", ""])

    lines.append("static constexpr GestureReference kGestureReferences[] = {")
    for gesture in gestures:
        array_name = f"k{gesture['id'].title().replace('_', '')}Segments"
        lines.append(f'    {{"{gesture["name"]}", {array_name}, {len(gesture["segments"])} }},')
    lines.extend(
        [
            "};",
            "",
            "static constexpr size_t kGestureReferenceCount = sizeof(kGestureReferences) / sizeof(kGestureReferences[0]);",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    header = render_header(load_gestures())
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    if not OUTPUT_FILE.exists() or OUTPUT_FILE.read_text(encoding="utf-8") != header:
        OUTPUT_FILE.write_text(header, encoding="utf-8")
        print(f"Generated {OUTPUT_FILE.relative_to(PROJECT_DIR)}")


main()
